# Generated by Django 6.0.3 on 2026-04-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('jobseeker', 'JobSeeker'), ('recruiter', 'Recruiter')], max_length=20)),
                ('resource', models.CharField(choices=[('jobs', 'Jobs'), ('resume', 'Resume & Documents'), ('applications', 'Job Applications'), ('user', 'user'), ('company', 'Company'), ('messages', 'Messages'), ('notifications', 'Notifications'), ('subscriptions', 'Subscriptions')], max_length=50)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'role_permissions',
                'ordering': ['role', 'resource'],
                'unique_together': {('role', 'resource')},
            },
        ),
    ]
