# Generated by Django 6.0.3 on 2026-04-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_loginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Logout', 'Logout'), ('Account Locked', 'Account Locked')], max_length=50),
        ),
    ]
