# Generated by Django 6.0.3 on 2026-04-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_loginlog_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
