# Generated by Django 6.0.3 on 2026-04-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
