# Generated by Django 6.0.3 on 2026-05-05 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'jobs_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=150)),
                ('job_type', models.CharField(choices=[('fulltime', 'FULLTIME'), ('parttime', 'PARTTIME'), ('remote', 'REMOTE'), ('contract', 'CONTRACT'), ('internship', 'INTERNSHIP')], default='FULLTIME', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'ENTRY'), ('mid', 'MID'), ('senior', 'SENIOR'), ('lead', 'LEAD')], default='MID', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('open', 'OPEN'), ('closed', 'CLOSED')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='Jobs.category')),
            ],
            options={
                'db_table': 'jobs_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
