# Generated by Django 6.0.3 on 2026-05-15 06:04

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_category_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('title_slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=150)),
                ('work_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], default='FULL_TIME', max_length=20)),
                ('work_mode', models.CharField(choices=[('ONSITE', 'Onsite'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=20)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Internship')], default='PERMANENT', max_length=20)),
                ('experience_level', models.CharField(choices=[('FRESHER', 'Fresher'), ('JUNIOR', 'Junior'), ('MID', 'Mid Level'), ('SENIOR', 'Senior'), ('LEAD', 'Lead')], default='MID', max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('skills_required', models.JSONField(blank=True, default=list, help_text="Example: ['Python', 'Django', 'PostgreSQL']")),
                ('tags', models.JSONField(blank=True, default=list, help_text="Example: ['backend', 'api', 'developer']")),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=10)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='Jobs.category')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
