# Generated by Django 6.0.3 on 2026-05-19 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_initial'),
        ('recruiter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title_slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('title_slug',), name='unique_job_title_slug'),
        ),
    ]
