# Generated by Django 6.0.3 on 2026-05-11 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_remove_category_description_remove_job_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='slug',
            new_name='title_slug',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='job',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['years_of_experience'], name='jobs_years_o_fc2b2a_idx'),
        ),
    ]
