# Generated by Django 6.0.3 on 2026-05-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobApplicationManagement', '0001_initial'),
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Jobs.job'),
        ),
    ]
