# Generated by Django 6.0.3 on 2026-05-15 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobApplicationManagement', '0002_initial'),
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_applications', to='jobseeker.jobseekerprofile'),
        ),
    ]
