# Generated by Django 6.0.3 on 2026-06-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplicationManagement', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
