# Generated by Django 6.0.3 on 2026-05-19 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number', regex='^\\d{10}$')]),
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(fields=('profile', 'qualification'), name='unique_qualification_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('profile', 'company_name', 'role', 'start_date'), name='unique_experience_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='preferredlocation',
            constraint=models.UniqueConstraint(fields=('profile', 'location_name'), name='unique_location_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('profile', 'skill_name'), name='unique_skill_per_profile'),
        ),
    ]
