# Generated by Django 6.0.3 on 2026-05-25 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('recruiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=300)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
                ('have_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='recruiter.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruiters',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['domain'], name='companies_domain_60b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_name_c7a1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='companies_industr_7891ac_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['location'], name='companies_locatio_df5de7_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiter',
            index=models.Index(fields=['full_name'], name='recruiters_full_na_acdb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiter',
            index=models.Index(fields=['designation'], name='recruiters_designa_0578ab_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiter',
            index=models.Index(fields=['is_admin'], name='recruiters_is_admi_138cbc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recruiter',
            unique_together={('user', 'company')},
        ),
    ]
